//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace TA.DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TransfereautoContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TransfereautoContainer object using the connection string found in the 'TransfereautoContainer' section of the application configuration file.
        /// </summary>
        public TransfereautoContainer() : base("name=TransfereautoContainer", "TransfereautoContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TransfereautoContainer object.
        /// </summary>
        public TransfereautoContainer(string connectionString) : base(connectionString, "TransfereautoContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TransfereautoContainer object.
        /// </summary>
        public TransfereautoContainer(EntityConnection connection) : base(connection, "TransfereautoContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }
    

    #endregion
    
    
}
